---
apiVersion: v1
kind: ConfigMap
metadata:
  name: books-api-configs
  namespace: books-api
data:
  POSTGRES_HOST: postgres
  POSTGRES_DB: postgres
  POSTGRES_PORT: "5432"
  APIHOST: "0.0.0.0"
  APIPORT: "5000"