apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: books-api
  labels:
    app: postgres
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  clusterIP: None
  selector:
    app: postgres